apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.fullname" . }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
        {{- toYaml .Values.matchLabels | nindent 8}}
  template:
    metadata:
      labels:
        {{- toYaml .Values.matchLabels | nindent 8}}
    spec:
      containers:
        - name: {{ .Values.container.name | default "default-name" }}
          image: {{ .Values.container.image | default "nginx:latest" }}
          imagePullPolicy: {{ .Values.container.pullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}