apiVersion: v1
kind: Secret

metadata:
  name: {{ include "mychart.fullname" . }}

type: Opaque

data:
  username: {{ .Values.data.username}}
  password: {{ .Values.data.password | b64enc | quote}}