input {
  beats {
    port => 5044
  }
}

filter {
  if "ERROR" in [message] {
    mutate {
      add_field => { "severity" => "ERROR" }
    }
  } else {
    mutate {
      add_field => { "severity" => "INFO" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "app-logs-%{+YYYY.MM.dd}"
  }
}