apiVersion: v1
kind: ConfigMap

metadata:
  name: demo-config

data:

  # .Values
  environment: "{{ .Values.environment }}"

  # .Chart
  chart-name: "{{ .Chart.Name }}"
  chart-version: "{{ .Chart.Version }}"

  # .Chart.AppVersion
  app-version: "{{ .Chart.AppVersion }}"

  # .Release
  release-name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"

  # .Template
  template-name: "{{ .Template.Name }}"

  # .Capabilities
  apps-v1-supported: "{{ .Capabilities.APIVersions.Has "apps/v1" }}"

  # .Files
  app.conf: |
{{ .Files.Get "config/app.conf" | indent 4 }}
