on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  print-info:
    name: Print Branch Name and Commit ID
    runs-on: ubuntu-latest
    steps:
      - name: Print Branch Name and Commit ID
        run: |
          echo "Branch Name: ${{ github.ref }}"
          echo "Commit ID:   ${{ github.sha }}"
